### ISSUE TITLE
Error: Can't send data because WebSocket is not opened.

### ISSUE THREAD

**Issue by Pensive** [materik/homebridge-harmonyhub-plugin#19]
I'm triggering this activity from a hue switch configured through homekit.

Wierd thing is if I open up the apple home app and select the Netflix Activity - it works. as does siri commands. 

It seems its only the Philips Hue switch homekit binding that comes up with the websocket error.

One in 10 times i run it - it works

But as far as having a Hue Switch which turns on the Netflix harmony activity - it basically never works. Wondering if there's a keep alive or something which needs to be added in?

```
[2019-1-30 21:07:18] [homebridge-harmonyhub-plugin] {HarmonyHub} start activitiy: <38150082>
(node:12088) UnhandledPromiseRejectionWarning: Error: Can't send data because WebSocket is not opened.
    at t.throwIf (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/webpack:/WebSocketAsPromised/src/utils.js:4:11)
    at e.throwIf (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/webpack:/WebSocketAsPromised/src/index.js:246:5)
    at e.send (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/webpack:/WebSocketAsPromised/src/index.js:237:10)
    at sendPacked (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/webpack:/WebSocketAsPromised/src/index.js:225:12)
    at e (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/webpack:/WebSocketAsPromised/node_modules/promise-controller/lib/bundle.prod.js:1:3152)
    at e._callFn (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/webpack:/WebSocketAsPromised/node_modules/promise-controller/lib/bundle.prod.js:1:1805)
    at e.call (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/webpack:/WebSocketAsPromised/src/requests.js:50:35)
    at e._createNewRequest (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/webpack:/WebSocketAsPromised/src/requests.js:24:17)
    at e.create (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/webpack:/WebSocketAsPromised/src/index.js:222:27)
    at HarmonyClient.startActivity (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/@harmonyhub/client-ws/dist/harmonyclient.js:161:31)
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/harmonyhub.js:153:24
    at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:12088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 131)
homebridge : TTY=pts/0 ; PWD=/var/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
pam_unix(sudo:session): session opened for user root by (uid=0)
```

**Comment by Pensive** [comment]
Case in point - now i've woken up the websocket - the hue switch buttons are working fine.

**Comment by materik** [comment]
Hmm. Do not know what you expect this package to do about this.

**Comment by Pensive** [comment]
It must be related to this package - I used to use Samsung Tizen plugin from tavicu like this reliably :-/

**Comment by Pensive** [comment]
Well - ive changed over to Nicoduj's plugin instead - if it does the same thing - we'll know its unlikley to be plugin related and something to with the hue homekit implementation.

**Comment by Pensive** [comment]
This morning I experienced a similar problem; last night the switch worked - this morning it doesn’t. The hue switch is telling HomeKit it is being clicked but the plugin doesn’t respond. There’s no error message on the other plugin - but it’s safe to say there’s something wrong with the websocket implementation on both plugins.

I’m going to revert to the local plugin now. Thanks anyway.

**Comment by Pensive** [comment]
Tell a lie - it still works but there’s a 20 second delay from a button press for some reason. I’ll post it on the other plugin as an issue.

I’m convinced they’re linked.

**Comment by materik** [comment]
Thanks for keeping me posted. If you ever feel that there is something I can do please reopen this issue. Until then I have a hard time follow what exactly goes wrong because I don't experience the same thing. Thanks!

**Comment by JacVid** [comment]
Hello,

thanks a lot for your work ! It is really helpfull to be able to use Harmony device through HomeKit.

I've been using your plugin for more than 2 month now, and in my case, during the last weeks, I get errors in the logs. Here under an exemple :

```
[6/30/2019, 8:44:40 AM] [homebridge-harmonyhub-plugin] {HarmonyHub} handleError: Error: Can't send data because WebSocket is not opened.
    at t.throwIf (/homebridge/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/index.js:2:43102)
    at e.value (/homebridge/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/index.js:2:13906)
    at e.value (/homebridge/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/index.js:2:13866)
    at /homebridge/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/index.js:2:13740
    at e.value (/homebridge/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/index.js:2:9621)
    at e.value (/homebridge/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/index.js:2:8353)
    at e.value (/homebridge/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/index.js:2:24841)
    at e.value (/homebridge/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/index.js:2:24270)
    at e.value (/homebridge/node_modules/homebridge-harmonyhub-plugin/node_modules/websocket-as-promised/dist/index.js:2:13651)
    at HarmonyClient.getCurrentActivity (/homebridge/node_modules/homebridge-harmonyhub-plugin/node_modules/@harmonyhub/client-ws/dist/harmonyclient.js:132:30)
    at /homebridge/node_modules/homebridge-harmonyhub-plugin/lib/harmonyhub.js:178:27
    at tryCallOne (/homebridge/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
    at /homebridge/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
    at flush (/homebridge/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Any idea of the problem ?

Thank you.

Jack

**Comment by acosmichippo** [comment]
I'm also seeing these web socket errors.  thought at first it might have something to do with my pihole, but I don't see any queries blocked from the Homebridge host.
