### ISSUE TITLE
2 hubs: States of one hub are often not recognized

### ISSUE THREAD

**Issue by mensa84** [materik/homebridge-harmonyhub-plugin#25]
Hello, I have 2 Harmony hubs.
The states of one hub are not refreshed in Homekit/Homebridge when I change the activity by Harmony Remote or Harmony App very often. The states are refreshed when I close the Home App on iPhone and re-open it. But that is a problem for automations.
Why are the states of the second hub not recognized automatically like one the first one?
Could it be a problem, that the names of some activities are the same on both hubs?

**Comment by materik** [comment]
could you please send me the log from your homebridge with debug enabled? maybe difficult to catch it in the act but it would be very helpful in fixing it.

**Comment by mensa84** [comment]
how can i do that?

**Comment by materik** [comment]
if you run your homebridge as `homebridge -D` and as soon as you notice that the other hub isn't responding, copy the latest log and paste it here.

**Comment by RXM307** [comment]
I believe I'm getting this same issue

$ /usr/bin/homebridge -U /var/homebridge -D
[2019-3-25 12:44:59] Loaded config.json with 0 accessories and 3 platforms.
[2019-3-25 12:44:59] ---
[2019-3-25 12:45:00] Loaded plugin: homebridge-harmonyhub-plugin
[2019-3-25 12:45:00] Registering platform 'homebridge-harmonyhub-plugin.HarmonyHub'
[2019-3-25 12:45:00] ---
[2019-3-25 12:45:00] Loaded plugin: homebridge-mi-outlet
[2019-3-25 12:45:00] ---
[2019-3-25 12:45:00] Loaded plugin: homebridge-server
[2019-3-25 12:45:00] Registering platform 'homebridge-server.Server'
[2019-3-25 12:45:00] ---
[2019-3-25 12:45:00] Plugin /usr/lib/node_modules/homebridge-ws requires Node version of ^10.15.0 which does not satisfy the current Node version of v9.11.2. You may need to upgrade your installation of Node.
[2019-3-25 12:45:01] Loaded plugin: homebridge-ws
[2019-3-25 12:45:01] Registering platform 'homebridge-ws.WS'
[2019-3-25 12:45:01] ---
[2019-3-25 12:45:01] Loading 3 platforms...
[2019-3-25 12:45:01] [Homebridge Server] Initializing Server platform...
[2019-3-25 12:45:01] [Lounge Room Harmony Hub] Initializing HarmonyHub platform...
[2019-3-25 12:45:01] [Lounge Room Harmony Hub] {Plugin}
[2019-3-25 12:45:01] [Weather] Initializing WS platform...
[2019-3-25 12:45:01] [Weather] homebridge-ws v2.1.5, node v9.11.2, homebridge v0.4.46
[2019-3-25 12:45:01] [Weather] homebridge-lib v4.0.5
[2019-3-25 12:45:01] [Weather] warning: not using recommended node v10.15.1 LTS
[2019-3-25 12:45:01] [Weather] config.json: {"platform":"WS","name":"Weather","openweathermap":{"apikey":"5e49faf9e959ec2f9c9aca4405111d29","locations":["Oxley, AU"]}}
[2019-3-25 12:45:04] [Weather] Oxley, AU: cached WsAccessoryOpenWeatherMap WS-OWM-OXLEYAU: {"location":"Oxley, AU"}
[2019-3-25 12:45:04] [Lounge Room Harmony Hub] {Accessory} fromAccessory
[2019-3-25 12:45:04] [Lounge Room Harmony Hub] {Accessory} <d189e73a-f34e-4e61-91e5-c914c01ab46a> <Dungeon Hub>
[2019-3-25 12:45:04] [Lounge Room Harmony Hub] {HarmonyHubAccessory} fromAccessory
[2019-3-25 12:45:04] [Lounge Room Harmony Hub] {HarmonyHubAccessory} <d189e73a-f34e-4e61-91e5-c914c01ab46a> <Dungeon Hub>
[2019-3-25 12:45:04] [Lounge Room Harmony Hub] {Plugin} configureAccessory: <Dungeon Hub>
[2019-3-25 12:45:04] [Lounge Room Harmony Hub] {Accessory} fromAccessory
[2019-3-25 12:45:04] [Lounge Room Harmony Hub] {Accessory} <f7c3e9f4-a23c-41cf-acef-397d0f08766c> <Lounge Room>
[2019-3-25 12:45:04] [Lounge Room Harmony Hub] {HarmonyHubAccessory} fromAccessory
[2019-3-25 12:45:04] [Lounge Room Harmony Hub] {HarmonyHubAccessory} <f7c3e9f4-a23c-41cf-acef-397d0f08766c> <Lounge Room>
[2019-3-25 12:45:04] [Lounge Room Harmony Hub] {Plugin} configureAccessory: <Lounge Room>
Setup Payload:
X-HM://0023IVTHABGKC
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:



























Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 032-78-078 │
    └────────────┘

[2019-3-25 12:45:04] [Lounge Room Harmony Hub] {Plugin} didFinishLaunching
[2019-3-25 12:45:04] [Lounge Room Harmony Hub] {Plugin} loadAccessories
[2019-3-25 12:45:04] [Lounge Room Harmony Hub] {HarmonyHub} finding hubs
[2019-3-25 12:45:04] [Weather] restored 1 accessories from cache
[2019-3-25 12:45:04] [Homebridge Server] is listening on: http://172.16.107.77:8765
[2019-3-25 12:45:04] Homebridge is running on port 51826.
[2019-3-25 12:45:04] [Weather] Oxley, AU History: /var/homebridge/accessories/history_WS-OWM-OXLEYAU.json: 369 entries
[2019-3-25 12:45:05] [Lounge Room Harmony Hub] {HarmonyHub} <Dungeon Hub> is online
[2019-3-25 12:45:05] [Lounge Room Harmony Hub] {HarmonyHub} <Lounge Room> is online
[2019-3-25 12:45:06] [Weather] warning: latest version: homebridge-ws v2.1.8
[2019-3-25 12:45:06] [Lounge Room Harmony Hub] {HarmonyHub} Found <2> hubs
[2019-3-25 12:45:06] [Lounge Room Harmony Hub] {HarmonyHub} <d189e73a-f34e-4e61-91e5-c914c01ab46a> <Dungeon Hub>
[2019-3-25 12:45:06] [Lounge Room Harmony Hub] {HarmonyHub} <f7c3e9f4-a23c-41cf-acef-397d0f08766c> <Lounge Room>
[2019-3-25 12:45:06] [Lounge Room Harmony Hub] {Plugin} use cache for <Dungeon Hub>
[2019-3-25 12:45:06] [Lounge Room Harmony Hub] {Plugin} use cache for <Lounge Room>
[2019-3-25 12:45:06] [Lounge Room Harmony Hub] {HarmonyHubAccessory} found <0> services
[2019-3-25 12:45:06] [Lounge Room Harmony Hub] {HarmonyHubAccessory} found <0> services
[2019-3-25 12:45:07] [Lounge Room Harmony Hub] {HarmonyHub} handleError: { HTTPError: Response code 417 (Expectation Failed)
    at EventEmitter.emitter.on (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/got/source/as-promise.js:74:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  name: 'HTTPError',
  host: '172.16.107.177:8088',
  hostname: '172.16.107.177',
  method: 'POST',
  path: '/',
  socketPath: undefined,
  protocol: 'http:',
  url: 'http://172.16.107.177:8088/',
  gotOptions:
   { path: '/',
     protocol: 'http:',
     slashes: true,
     auth: null,
     host: '172.16.107.177:8088',
     port: '8088',
     hostname: '172.16.107.177',
     hash: null,
     search: null,
     query: null,
     pathname: '/',
     href: 'http://172.16.107.177:8088/',
     retry:
      { retries: [Function],
        methods: [Set],
        statusCodes: [Set],
        errorCodes: [Set],
        maxRetryAfter: 5000 },
     headers:
      { 'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
        'content-type': 'application/json',
        accept: 'text/plain',
        origin: 'http//:localhost.nebula.myharmony.com',
        'accept-encoding': 'gzip, deflate',
        'content-length': 54 },
     hooks:
      { beforeRequest: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: [],
        beforeError: [],
        init: [] },
     decompress: true,
     throwHttpErrors: true,
     followRedirect: true,
     stream: false,
     form: false,
     json: true,
     cache: false,
     useElectronNet: false,
     method: 'POST',
     body: '{"id":0,"cmd":"connect.discoveryinfo?get","params":{}}',
     gotTimeout: { request: 5000 } },
  statusCode: 417,
  statusMessage: 'Expectation Failed',
  headers:
   { 'access-control-allow-headers': 'origin, content-type, accept',
     'access-control-allow-method': 'POST, OPTIONS',
     'access-control-allow-origin': 'http//:localhost.nebula.myharmony.com',
     'content-length': '16' },
  body: { code: '417' } }
[2019-3-25 12:45:07] [Lounge Room Harmony Hub] {HarmonyHub} get activities
[2019-3-25 12:45:07] [Lounge Room Harmony Hub] {HarmonyHub} handleError: TypeError: Cannot read property 'getActivities' of undefined
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/harmonyhub.js:130:27
    at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:176:11)
[2019-3-25 12:45:07] [Lounge Room Harmony Hub] {HarmonyHubAccessory} update states for <0> services
[2019-3-25 12:45:07] [Lounge Room Harmony Hub] {HarmonyHubAccessory} handle state changes for <0> services
[2019-3-25 12:45:07] [Lounge Room Harmony Hub] {HarmonyHub} handleError: TypeError: Cannot read property 'getCurrentActivity' of undefined
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/harmonyhub.js:178:27
    at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:176:11)
[2019-3-25 12:45:07] [Lounge Room Harmony Hub] {HarmonyHub} handleError: { HTTPError: Response code 417 (Expectation Failed)
    at EventEmitter.emitter.on (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/got/source/as-promise.js:74:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  name: 'HTTPError',
  host: '172.16.107.165:8088',
  hostname: '172.16.107.165',
  method: 'POST',
  path: '/',
  socketPath: undefined,
  protocol: 'http:',
  url: 'http://172.16.107.165:8088/',
  gotOptions:
   { path: '/',
     protocol: 'http:',
     slashes: true,
     auth: null,
     host: '172.16.107.165:8088',
     port: '8088',
     hostname: '172.16.107.165',
     hash: null,
     search: null,
     query: null,
     pathname: '/',
     href: 'http://172.16.107.165:8088/',
     retry:
      { retries: [Function],
        methods: [Set],
        statusCodes: [Set],
        errorCodes: [Set],
        maxRetryAfter: 5000 },
     headers:
      { 'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
        'content-type': 'application/json',
        accept: 'text/plain',
        origin: 'http//:localhost.nebula.myharmony.com',
        'accept-encoding': 'gzip, deflate',
        'content-length': 54 },
     hooks:
      { beforeRequest: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: [],
        beforeError: [],
        init: [] },
     decompress: true,
     throwHttpErrors: true,
     followRedirect: true,
     stream: false,
     form: false,
     json: true,
     cache: false,
     useElectronNet: false,
     method: 'POST',
     body: '{"id":0,"cmd":"connect.discoveryinfo?get","params":{}}',
     gotTimeout: { request: 5000 } },
  statusCode: 417,
  statusMessage: 'Expectation Failed',
  headers:
   { 'access-control-allow-headers': 'origin, content-type, accept',
     'access-control-allow-method': 'POST, OPTIONS',
     'access-control-allow-origin': 'http//:localhost.nebula.myharmony.com',
     'content-length': '16' },
  body: { code: '417' } }
[2019-3-25 12:45:07] [Lounge Room Harmony Hub] {HarmonyHub} get activities
[2019-3-25 12:45:07] [Lounge Room Harmony Hub] {HarmonyHub} handleError: TypeError: Cannot read property 'getActivities' of undefined
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/harmonyhub.js:130:27
    at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:176:11)
[2019-3-25 12:45:07] [Lounge Room Harmony Hub] {HarmonyHubAccessory} update states for <0> services
[2019-3-25 12:45:07] [Lounge Room Harmony Hub] {HarmonyHubAccessory} handle state changes for <0> services
[2019-3-25 12:45:07] [Lounge Room Harmony Hub] {HarmonyHub} handleError: TypeError: Cannot read property 'getCurrentActivity' of undefined
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/harmonyhub.js:178:27
    at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:176:11)
[2019-3-25 12:45:07] [Weather] Oxley, AU: {"coord":{"lon":152.97,"lat":-27.56},"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"base":"stations","main":{"temp":32.61,"pressure":1013,"humidity":62,"temp_min":29,"temp_max":35},"visibility":10000,"wind":{"speed":6.2,"deg":40},"clouds":{"all":40},"dt":1553481904,"sys":{"type":1,"id":9485,"message":0.0048,"country":"AU","sunrise":1553457223,"sunset":1553500489},"id":2154050,"name":"Oxley","cod":200}
[2019-3-25 12:45:07] [Weather] Oxley, AU Temperature: set Current Temperature from 32.4°C to 32.6°C
[2019-3-25 12:45:07] [Weather] Oxley, AU Weather: set Last Updated from Mon Mar 25 2019 12:39:23 to Mon Mar 25 2019 12:45:04
^C[2019-3-25 12:45:10] Got SIGINT, shutting down Homebridge...
[2019-3-25 12:45:10] [Weather] Oxley, AU History: /var/homebridge/accessories/history_WS-OWM-OXLEYAU.json: 369 entries
^C[2019-3-25 12:45:14] Got SIGINT, shutting down Homebridge...

**Comment by materik** [comment]
Sorry for my lack in response. Since this is so old I would guess you have moved on and it's fine to close it. If not, please reopen this. Thanks!
