### ISSUE TITLE
TypeError: self.name is not a function

### ISSUE THREAD

**Issue by arronpitman** [materik/homebridge-harmonyhub-plugin#34]
Fresh install of homebridge 1.0.4 and this plugin on Ubuntu 18.04.4 LTS. 

Receive this message in the logs: 

[5/2/2020, 5:43:38 PM] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <1> hubs
[5/2/2020, 5:43:38 PM] [homebridge-harmonyhub-plugin] {HarmonyHub} <0260e285-54c5-4613-bd62-8690239aabd1> <Harmony Hub>
[5/2/2020, 5:43:38 PM] [homebridge-harmonyhub-plugin] {HarmonyHub} create new client for <Harmony Hub>
[5/2/2020, 5:43:39 PM] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <1> activities: <Watch TV>
[5/2/2020, 5:43:39 PM] [homebridge-harmonyhub-plugin] {HarmonyHubAccessory} adding <1> activities
[5/2/2020, 5:43:39 PM] [homebridge-harmonyhub-plugin] {HarmonyHubAccessory} addActivity <Watch TV>
[5/2/2020, 5:43:39 PM] [homebridge-harmonyhub-plugin] {HarmonyHubAccessory} loadActivities: TypeError: self.name is not a function
    at new ActivityService (/usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/activity-service.js:15:64)
    at Accessory._this.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:270:11)
    at PlatformAccessory.addService (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:92:41)
    at Accessory.addService (/usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/accessory.js:38:49)
    at HarmonyHubAccessory.addActivity (/usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/harmonyhub-accessory.js:47:27)
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/harmonyhub-accessory.js:140:37
    at arrayMap (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/lodash/lodash.js:9556:14)
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/harmonyhub-accessory.js:139:30
    at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

Config is: 

{
    "bridge": {
        "name": "Homebridge 7047",
        "username": "0E:55:2B:02:70:47",
        "port": 51828,
        "pin": "155-56-911"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "platform": "HarmonyHub",
            "name": "homebridge-harmonyhub-plugin"
        }
    ]
}

Not sure what I've done wrong here.

**Comment by nicoh88** [comment]
Same here.

**What was wrong?**
