### ISSUE TITLE
My first attempt at install 

### ISSUE THREAD

**Issue by Tesla-P100FX** [materik/homebridge-harmonyhub-plugin#37]
**Confi.json added**

"platforms": [
    {
        "platform": "HarmonyHub",
        "name": "homebridge-harmonyhub-plugin"
    }
]
**Getting:**

HarmonyHubAccessory} loadActivities: TypeError: self.name is not a function
    at new ActivityService (C:\Users\Xxxxx\AppData\Roaming\npm\node_modules\homebridge-harmonyhub-plugin\lib\activity-service.js:15:64)
    at Accessory._this.addService (C:\Users\Xxxxx\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:267:11)
    at PlatformAccessory.addService (C:\Users\Xxxxx\AppData\Roaming\npm\node_modules\homebridge\src\platformAccessory.ts:92:41)
    at Accessory.addService (C:\Users\Xxxxx\AppData\Roaming\npm\node_modules\homebridge-harmonyhub-plugin\lib\accessory.js:38:49)
    at HarmonyHubAccessory.addActivity (C:\Users\Xxxxx\AppData\Roaming\npm\node_modules\homebridge-harmonyhub-plugin\lib\harmonyhub-accessory.js:47:27)
    at C:\Users\Xxxxx\AppData\Roaming\npm\node_modules\homebridge-harmonyhub-plugin\lib\harmonyhub-accessory.js:140:37
    at arrayMap (C:\Users\Xxxxx\AppData\Roaming\npm\node_modules\homebridge-harmonyhub-plugin\node_modules\lodash\lodash.js:639:23)
    at Function.map (C:\Users\Xxxxx\AppData\Roaming\npm\node_modules\homebridge-harmonyhub-plugin\node_modules\lodash\lodash.js:9556:14)
    at C:\Users\Xxxxx\AppData\Roaming\npm\node_modules\homebridge-harmonyhub-plugin\lib\harmonyhub-accessory.js:139:30
    at tryCallOne (C:\Users\Xxxxx\AppData\Roaming\npm\node_modules\homebridge-harmonyhub-plugin\node_modules\promise\lib\core.js:37:12)

**Comment by Joop1953** [comment]
I have the same problem. Nobody reacted to this.
Is there a solution?

**Comment by materik** [comment]
Sorry for my lack of response. Should be fixed now!
