### ISSUE TITLE
Homebridge 1.3.0 error

### ISSUE THREAD

**Issue by gdotp01** [materik/homebridge-harmonyhub-plugin#41]
I updated to 1.3.0 and have been seeing an error in the log file since. It happens regularly but I think the plugin is still functioning 

[22/02/2021, 22:39:28] [homebridge-harmonyhub-plugin] {HarmonyHubAccessory} updateStates: RangeError: Maximum call stack size exceeded
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:661:56)
    at Characteristic.emit (events.js:327:22)
    at Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1358:10)
    at Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at Service.set (/usr/local/lib/node_modules/homebridge-harmonyhub-plugin/lib/service.js:26:18)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub-plugin/lib/service.js:47:18)
    at Characteristic.emit (events.js:327:22)
    at Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1358:10)
    at Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at Service.set (/usr/local/lib/node_modules/homebridge-harmonyhub-plugin/lib/service.js:26:18)

**Comment by gdotp01** [comment]
I’ll update this. The buttons are still in HomeKit but nothing works

**Comment by materik** [comment]
Hey. Sorry for late response. Would you mind installing and testing out 0.5.10. Thanks

**Comment by gdotp01** [comment]
Hi. Sorry I don’t have it installed any longer as it was causing too many issues.

**Comment by materik** [comment]
I understand. thanks anyway, I think this should be fixed now at least.
