### ISSUE TITLE
loadAccessories: TypeError

### ISSUE THREAD

**Issue by gdavids57** [materik/homebridge-harmonyhub-plugin#42]
After upgrading to Homebridge 1.3.2, I started getting the following error in the log

_[3/6/2021, 9:04:53 AM] [homebridge-harmonyhub-plugin] {HarmonyHubAccessory} updateStates: RangeError: Maximum call stack size exceeded_

I uninstalled the plugin and reinstalled. Upon restart, I received the following in the log

[3/6/2021, 11:06:12 AM] Loaded plugin: homebridge-harmonyhub-plugin@0.5.8
[3/6/2021, 11:06:12 AM] Registering platform 'homebridge-harmonyhub-plugin.HarmonyHub'
[3/6/2021, 11:06:14 AM] [homebridge-harmonyhub-plugin] Initializing HarmonyHub platform...
[3/6/2021, 11:06:16 AM] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <1> hubs
[3/6/2021, 11:06:16 AM] [homebridge-harmonyhub-plugin] {HarmonyHub} <a8df0c1f-a810-40f8-a84f-1cdf614e1744> <Family Room>
[3/6/2021, 11:06:16 AM] [homebridge-harmonyhub-plugin] {Plugin} loadAccessories: TypeError: Cannot read property 'name' of undefined
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/plugin.js:51:61

Config entry is 
{
            "platform": "HarmonyHub",
            "name": "HarmonyHub"
},

Server configuration

OS | Raspbian GNU/Linux Buster (10)
Hostname: raspberrypi
Node.js Version: v14.15.4
Npm Version: v6.14.10
Homebridge Version: 1.3.2

**Comment by tkaudioservices** [comment]
I also get something similar

```
[06/04/2021, 20:07:30] [HarmonyHub] {HarmonyHubAccessory} updateStates: RangeError: Maximum call stack size exceeded
    at On.emit (events.js:264:44)
    at On.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1399:10)
    at Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at Service.set (/usr/local/lib/node_modules/homebridge-harmonyhub-plugin/lib/service.js:26:18)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub-plugin/lib/service.js:47:18)
    at On.emit (events.js:327:22)
    at On.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1399:10)
    at Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at Service.set (/usr/local/lib/node_modules/homebridge-harmonyhub-plugin/lib/service.js:26:18)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub-plugin/lib/service.js:47:18)
```

**Comment by materik** [comment]
Hey. Sorry for late response. Would you mind installing and testing out 0.5.10. Thanks
